on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: "Build and release flutter app"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '12.x'
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: '${{ github.actor }}'
          server-password: '${{ secrets.GITHUB_TOKEN }}'
          overwrite-settings: true
          job-status: 'success'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.5'
      - run: flutter pub get
      - run: flutter --version
      - run: flutter build apk --debug --split-per-abi
      - name: push to release
        uses: ncipollo/release-action@v1.8.10
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          tag: v0.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
